# Generated by Django 4.2.6 on 2023-10-20 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rest_reamrk', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(default='', max_length=15)),
                ('nearby_schools', models.CharField(default='', max_length=20)),
                ('rest_image', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('avg_cost', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('avg_score1', models.FloatField(blank=True, null=True)),
                ('avg_score2', models.FloatField(blank=True, null=True)),
                ('avg_score3', models.FloatField(blank=True, null=True)),
                ('avg_score4', models.FloatField(blank=True, null=True)),
                ('avg_score', models.FloatField(blank=True, null=True)),
                ('last_comment_time', models.DateTimeField(blank=True, null=True)),
                ('high_count', models.PositiveIntegerField(default=0)),
                ('mid_count', models.PositiveIntegerField(default=0)),
                ('low_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('most_recom', models.CharField(blank=True, max_length=20, null=True)),
                ('dining_methods', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('per_person_cost', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('score_1', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('score_2', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('score_3', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('score_4', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('comment_time', models.DateTimeField(blank=True, null=True)),
                ('recommend', models.CharField(blank=True, max_length=20, null=True)),
                ('like_count', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_create.post')),
            ],
        ),
    ]
