# Generated by Django 4.2.6 on 2023-10-20 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_create', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
