# Generated by Django 4.2.5 on 2023-10-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_create", "0003_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="id",
        ),
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
