# Generated by Django 4.2.5 on 2023-10-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_create", "0004_remove_school_id_alter_school_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="school_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="dining_methods",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
