# Generated by Django 4.2.5 on 2023-10-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_create", "0007_comment_nickname_post_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
