# Generated by Django 4.2.5 on 2023-10-26 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_create', '0009_rename_rest_reamrk_post_rest_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(default='请编辑您的手机号', max_length=15)),
                ('school', models.CharField(default='请编辑您的学校', max_length=100, primary_key=True, serialize=False)),
                ('register_date', models.DateTimeField(blank=True, null=True)),
                ('user_image', models.ImageField(blank=True, default='./static/images/default_user_image.jpg', null=True, upload_to='user_images/')),
            ],
        ),
        migrations.CreateModel(
            name='User_Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('collect_time', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_create.post')),
            ],
        ),
    ]
