# Generated by Django 4.2.5 on 2023-10-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_create', '0010_user_info_user_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='contact',
            field=models.CharField(default='请编辑您的手机号', max_length=30),
        ),
    ]
