# Generated by Django 4.2.5 on 2023-10-26 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_create', '0011_alter_user_info_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='school',
            new_name='school_name',
        ),
    ]
