# Generated by Django 4.2.5 on 2023-10-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_create', '0012_rename_school_user_info_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_fav',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_fav',
            name='user_name',
            field=models.CharField(blank=True, default=2, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_info',
            name='school_name',
            field=models.CharField(default='请编辑您的学校', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
