# Generated by Django 4.2.5 on 2023-10-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_create', '0014_alter_user_info_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_image',
            field=models.ImageField(blank=True, default='./user_images/default_user_image.jpg', null=True, upload_to='user_images/'),
        ),
    ]
