# Generated by Django 4.2.5 on 2023-10-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_create', '0015_alter_user_info_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_fav',
            name='post',
        ),
        migrations.AddField(
            model_name='user_fav',
            name='store_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
