# Generated by Django 4.2.5 on 2023-10-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_create', '0017_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
