# Generated by Django 4.2.5 on 2023-10-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post_create", "0018_remove_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_fav",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user_fav",
            name="user_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
